### ISSUE TITLE
Composer installs appear to be cached incorrectly

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe-labs/silverstripe-travis-support#36]
Hooray for introducing my own issues! This leads on from https://github.com/silverstripe-labs/silverstripe-travis-support/pull/35.

When running a travis build using the new `--prefer-source` option, Composer attempts to download the _source_ version of the package and sometimes fails - falling back to the _dist_ version.

[Travis build log](https://travis-ci.org/bigfork/silverstripe-oauth-login/jobs/145853708#L193-L202):
```
- Installing silverstripe/framework (3.3.x-dev de61551)
    Cloning de6155188552003c294f115588dcdab9a79cef44
    Failed to download silverstripe/framework from source: Failed to execute git checkout 'de6155188552003c294f115588dcdab9a79cef44' -- && git reset --hard 'de6155188552003c294f115588dcdab9a79cef44' --

fatal: Not a git repository (or any of the parent directories): .git

    Now trying to download from dist
  - Installing silverstripe/framework (3.3.x-dev de61551)
    Downloading
    Extracting archive
```

I’ve got no idea why that would fail, the commit definitely exists and `--verbose` doesn’t give any more info than the above. You can see from the rest of [the log](https://travis-ci.org/bigfork/silverstripe-oauth-login/jobs/145853708#L193-L202) that some packages work and some don’t (it doesn’t seem to be related to whether they’re using tags or commit hashes).

I’ve copied the generated composer.json and run it locally and it works absolutely fine. That, and the `Not a git repository` error message, makes me think some caching is going on that’s downloading the _dist_ copy when Composer thinks it’s downloading the _source_ copy.

I don’t know if this is an issue with this repo, Travis, Composer, or me 😆.

**Comment by tractorcow** [comment]
It normally happens when rate limited; You can get around it sometimes by setting up a github api key against your travis repo.

Try doing this on https://travis-ci.org/bigfork/silverstripe-oauth-login/settings

![image](https://cloud.githubusercontent.com/assets/936064/17317566/5a4448e6-58d3-11e6-8e97-62454ebb3aad.png)

And create your token from github. In the top menu to the right, click the tools icon (Account Settings).
Click on “Applications” in the sidebar (to the left). In the box with the title “Personal Access Tokens”, press the “Create new token” button.

Nothing is cached because travis ci instances are thrown away, so no caches persist between builds. You can get around it, but we opt to not do so, as we end up with stale builds more often than not...

Anyway, ping me if you get stuck. :)

**Comment by kinglozzer** [comment]
I’m still struggling 😢. I [added the token](https://travis-ci.org/bigfork/silverstripe-oauth-login/jobs/147511639#L127), but it’s still loading some repos from [dist instead of source](https://travis-ci.org/bigfork/silverstripe-oauth-login/jobs/147511639#L199). I’ve opened an issue on the Composer repo too https://github.com/composer/composer/issues/5546

**Comment by tractorcow** [comment]
Yeah there's still some problem going on here.


`    Failed to download silverstripe/framework from source: Failed to execute git checkout '96b061ffffd472f917273b43790f5aaa2f9f89b4' -- && git reset --hard '96b061ffffd472f917273b43790f5aaa2f9f89b4' --`

**Comment by tractorcow** [comment]
Ah, maybe there is an issue with composer... regarding that ticket you raised. Hope it bears some fruit. :)
